global:
  scrape_interval: 15s  # How frequently Prometheus should scrape targets (default is 15s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      - targets: ['node-exporter:9100']
      - targets: ['docker-host:9323']
      - targets: ['pushgateway:9091']
      - targets: ['cadvisor:8080']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
