global:
  resolve_timeout: 5m

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'default-route'

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - api_url: 'https://api.telegram.org/bot6531547225:AAH6VxISLtbde24dSuRaF-NUuWu3VU31iws/sendMessage'
    chat_id: '6339982499'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'prod', 'instance']
