global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
            - targets: ['10.33.11.3:9100','10.33.11.2:9100','10.33.11.4:9100','10.33.11.6:9100','10.33.11.5:9100','10.33.11.7:9100','10.33.11.8:9100','172.31.25.106:9100']

rule_files:
  - /etc/prometheus/alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]
groups:
- name: example
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
